# Generated by Django 4.1.7 on 2023-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_item_order_orderitem_order_items_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
    ]
