# Generated by Django 4.1.7 on 2023-03-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model_year', models.IntegerField()),
                ('price_per_hour', models.IntegerField()),
            ],
        ),
    ]
