# Generated by Django 4.1.7 on 2023-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='class_type',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
