# Generated by Django 4.1.7 on 2023-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_class_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('msg', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
    ]
