# Generated by Django 4.1.7 on 2023-08-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_items_alter_orderitem_item'),
        ('home', '0009_remove_orderitem_item_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
