# Generated by Django 4.1.7 on 2023-08-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_item_categories_delete_category_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
