# Generated by Django 4.1.7 on 2023-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
