# Generated by Django 4.1.7 on 2023-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_items_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
